# Generated by Django 4.0.2 on 2022-02-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='describtion',
            new_name='description',
        ),
    ]
