# Generated by Django 4.0.2 on 2022-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_word_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
