# Generated by Django 4.0.2 on 2022-02-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_word_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='context',
        ),
        migrations.DeleteModel(
            name='WordContext',
        ),
    ]
